# Generated by Django 4.2.2 on 2023-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='hashed_otp',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
