# Generated by Django 4.2.2 on 2023-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_password_user_hashed_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_otp',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
